services:
  # Backend Service
  - type: web
    name: pmip-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PORT
        value: 8000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: USE_SUPABASE_AUTH
        value: "true"

  # Frontend Service
  - type: web
    name: pmip-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://pmip-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
