services:
  # Backend Service
  - type: web
    name: pmip-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd backend && pip install -r requirements.txt
    startCommand: |
      cd backend && gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: USE_SUPABASE_AUTH
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend Service
  - type: web
    name: pmip-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: |
      npm install && npm run build
    startCommand: |
      npm run start
    envVars:
      - key: NODE_VERSION
        value: 18.12.0
    routes:
      - type: rewrite
        source: /api/*
        destination: https://pmip-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html